"use client";

import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/layout/index.jsx';
import { Button } from '@/components/ui/Button';
import toast from 'react-hot-toast';

export default function OperationsPage() {
  const [thresholds, setThresholds] = useState({ redBelow: 40, yellowBelow: 70 }); const [leaves, setLeaves] = useState<Array<{ _id: string; startDate: string; endDate: string; leaveType: string; reason: string; status: string; teacherId?: { firstName: string; lastName: string } }>>([]); const [saving, setSaving] = useState(false);
  const request = async (path: string, init?: RequestInit) => { const token = localStorage.getItem('token'); const response = await fetch(`/api/v1${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...(init?.headers || {}) } }); return response.json(); };
  const load = async () => { try { const [settings, leave] = await Promise.all([request('/system-config'), request('/operations/leave')]); setThresholds(settings.data?.performanceSettings || { redBelow: 40, yellowBelow: 70 }); setLeaves(leave.data || []); } catch { toast.error('Failed to load operations data'); } };
  // Initial API hydration is intentionally asynchronous; `load` owns the pending/error state.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, []);
  const save = async () => { if (thresholds.redBelow < 0 || thresholds.redBelow >= thresholds.yellowBelow || thresholds.yellowBelow > 100) return toast.error('Use 0 ≤ red threshold < yellow threshold ≤ 100.'); setSaving(true); try { const result = await request('/system-config', { method: 'PUT', body: JSON.stringify({ performanceSettings: thresholds }) }); if (!result.success) throw new Error(); toast.success('Flag thresholds saved'); } catch { toast.error('Could not save thresholds'); } finally { setSaving(false); } };
  const review = async (id: string, status: string) => { try { const result = await request(`/operations/leave/${id}`, { method: 'PUT', body: JSON.stringify({ status }) }); if (!result.success) throw new Error(); toast.success(`Leave ${status.toLowerCase()}`); load(); } catch { toast.error('Could not update leave request'); } };
  return <div className="mx-auto max-w-7xl space-y-8"><PageHeader title="Academic operations" subtitle="Control performance thresholds and teacher leave approvals." />
    <section className="card p-6 max-w-2xl"><h2 className="font-display text-lg font-semibold">Topic flag thresholds</h2><p className="mt-1 text-sm text-surface-500">Red is below the first threshold. Yellow includes both boundary values up to the second threshold.</p><div className="mt-5 grid grid-cols-2 gap-4"><label><span className="form-label">Red below (%)</span><input className="form-input" type="number" min="0" max="99" value={thresholds.redBelow} onChange={e => setThresholds(v => ({ ...v, redBelow: Number(e.target.value) }))} /></label><label><span className="form-label">Yellow through (%)</span><input className="form-input" type="number" min="1" max="100" value={thresholds.yellowBelow} onChange={e => setThresholds(v => ({ ...v, yellowBelow: Number(e.target.value) }))} /></label></div><Button className="mt-5" loading={saving} onClick={save}>Save thresholds</Button></section>
    <section className="card overflow-hidden"><div className="p-6"><h2 className="font-display text-lg font-semibold">Teacher leave requests</h2></div><div className="table-wrapper border-x-0 border-b-0 rounded-none"><table className="data-table"><thead><tr><th>Teacher</th><th>Dates</th><th>Type</th><th>Reason</th><th>Status</th><th>Decision</th></tr></thead><tbody>{leaves.map(leave => <tr key={leave._id}><td>{leave.teacherId?.firstName} {leave.teacherId?.lastName}</td><td>{new Date(leave.startDate).toLocaleDateString('en-IN')} – {new Date(leave.endDate).toLocaleDateString('en-IN')}</td><td>{leave.leaveType}</td><td>{leave.reason}</td><td><span className="badge badge-surface">{leave.status}</span></td><td>{leave.status === 'PENDING' && <div className="flex gap-2"><button className="btn-success btn-sm" onClick={() => review(leave._id, 'APPROVED')}>Approve</button><button className="btn-danger btn-sm" onClick={() => review(leave._id, 'REJECTED')}>Reject</button></div>}</td></tr>)}{!leaves.length && <tr><td colSpan={6} className="py-8 text-center text-surface-500">No leave requests awaiting review.</td></tr>}</tbody></table></div></section>
  </div>;
}
