"use client";
import { useEffect, useMemo, useState } from 'react';
import { Calendar, ChevronDown } from 'lucide-react';
import toast from 'react-hot-toast';
import { PageHeader } from '@/components/layout/index.jsx';
import { teacherAPI } from '@/api/teacher';

const time = (value?: string) => value ? new Date(value).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : '—';
export default function TeacherAttendancePage() {
  const [items, setItems] = useState<any[]>([]); const [open, setOpen] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { teacherAPI.getAttendance({}).then(r => setItems(r.data?.data || r.data || [])).catch(() => toast.error('Attendance could not be loaded.')).finally(() => setLoading(false)); }, []);
  const month = new Date().getMonth(), year = new Date().getFullYear();
  const current = useMemo(() => items.filter(item => { const d = new Date(item.date); return d.getMonth() === month && d.getFullYear() === year; }), [items, month, year]);
  const stats = useMemo(() => current.flatMap(item => item.records || []).reduce((a, r) => ({ ...a, total: a.total + 1, present: a.present + (r.status === 'present' ? 1 : 0), absent: a.absent + (r.status === 'absent' ? 1 : 0) }), { total: 0, present: 0, absent: 0 }), [current]);
  return <div className="mx-auto max-w-7xl space-y-6"><PageHeader title="Attendance" subtitle="Current-month class attendance with student join, leave and rejoin records." />
    <div className="grid gap-4 sm:grid-cols-3">{[['Recorded', stats.total, 'All student class records'], ['Present', stats.present, 'Joined within 10 minutes'], ['Absent', stats.absent, 'Late / absent records']].map(([label, count, hint]) => <div key={String(label)} className="card p-5"><p className="text-sm text-surface-500">{label}</p><p className="mt-1 text-3xl font-display font-semibold">{count}</p><p className="mt-1 text-xs text-surface-400">{hint}</p></div>)}</div>
    <section className="card overflow-hidden"><div className="flex items-center gap-3 p-6"><Calendar className="text-brand-600" /><div><h2 className="font-display text-lg font-semibold">{new Intl.DateTimeFormat('en-IN', { month: 'long', year: 'numeric' }).format(new Date())} class register</h2><p className="text-sm text-surface-500">Open a class to view every student’s recorded activity.</p></div></div>{loading ? <p className="p-8 text-surface-500">Loading attendance…</p> : current.length ? <div className="divide-y">{current.map(item => { const records = item.records || []; const expanded = open === item._id; return <div key={item._id}><button className="flex w-full items-center justify-between gap-4 px-6 py-4 text-left hover:bg-surface-50" onClick={() => setOpen(expanded ? null : item._id)}><div><p className="font-semibold">{new Date(item.date).toLocaleDateString('en-IN')} · {item.subjectId?.name || 'General'}</p><p className="text-sm text-surface-500">{item.batchId?.name || 'Batch not assigned'} · {records.length} students</p></div><ChevronDown className={expanded ? 'rotate-180 transition-transform' : 'transition-transform'} /></button>{expanded && <div className="border-t bg-surface-50 p-4"><div className="table-wrapper"><table className="data-table"><thead><tr><th>Student</th><th>Roll no.</th><th>Status</th><th>First join</th><th>Leave / rejoin history</th></tr></thead><tbody>{records.map((record: any, index: number) => <tr key={record.studentId?._id || index}><td>{record.studentId?.firstName} {record.studentId?.lastName}</td><td>{record.studentId?.admissionNumber || record.studentId?.metadata?.rollNo || '—'}</td><td><span className="badge badge-surface">{record.status}</span></td><td>{time(record.joinedAt)}</td><td>{record.joinEvents?.length ? record.joinEvents.map((event: any, i: number) => <span key={i} className="mr-2 inline-block text-xs">Join {time(event.joinedAt)} → Leave {time(event.leftAt)}</span>) : 'No leave/rejoin event recorded'}</td></tr>)}</tbody></table></div></div>}</div>; })}</div> : <p className="p-10 text-center text-surface-500">No attendance records for this month.</p>}</section></div>;
}
