"use client";

import { useEffect, useState } from 'react';
import { Calendar, Send } from 'lucide-react';
import toast from 'react-hot-toast';
import { PageHeader } from '@/components/layout/index.jsx';
import { Button } from '@/components/ui/Button';
import { teacherAPI } from '@/api/teacher';

type Attendance = { _id: string; date: string; batchId?: { name?: string; section?: string }; subjectId?: { name?: string }; records?: Array<{ studentId?: { _id?: string; firstName?: string; lastName?: string }; status: string }> };
type Leave = { _id: string; leaveType: string; startDate: string; endDate: string; reason: string; status: string; reviewNote?: string };

export default function TeacherAttendancePage() {
  const [attendance, setAttendance] = useState<Attendance[]>([]); const [leaves, setLeaves] = useState<Leave[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ leaveType: 'SICK', startDate: '', endDate: '', reason: '' });
  const load = async () => { setLoading(true); try { const [a, l] = await Promise.all([teacherAPI.getAttendance({}), teacherAPI.getLeaveRequests()]); setAttendance(a.data?.data || a.data || []); setLeaves(l.data?.data || l.data || []); } catch { toast.error('Attendance or leave requests could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!form.startDate || !form.endDate || !form.reason.trim()) return toast.error('Add dates and a reason.'); setSaving(true); try { await teacherAPI.requestLeave(form); toast.success('Leave request sent to the admin.'); setForm({ leaveType: 'SICK', startDate: '', endDate: '', reason: '' }); await load(); } catch (error: any) { toast.error(error?.response?.data?.message || 'Leave request could not be submitted.'); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-7xl space-y-8"><PageHeader title="Attendance & leave" subtitle="Review attendance for your assigned classes and send leave requests to the admin." />
    <div className="grid gap-8 xl:grid-cols-[1.5fr_1fr]"><section className="card overflow-hidden"><div className="flex items-center justify-between p-6"><div><h2 className="font-display text-lg font-semibold">Class attendance</h2><p className="mt-1 text-sm text-surface-500">Only attendance for classes assigned to you is visible.</p></div><Calendar className="text-brand-600" /></div><div className="table-wrapper border-x-0 border-b-0 rounded-none"><table className="data-table"><thead><tr><th>Date</th><th>Batch</th><th>Subject</th><th>Students</th><th>Present / late</th></tr></thead><tbody>{attendance.map(item => { const records = item.records || []; const attended = records.filter(record => ['present', 'late'].includes(record.status)).length; return <tr key={item._id}><td>{new Date(item.date).toLocaleDateString('en-IN')}</td><td>{item.batchId?.name || '—'}{item.batchId?.section ? ` • ${item.batchId.section}` : ''}</td><td>{item.subjectId?.name || 'General'}</td><td>{records.length}</td><td>{attended}</td></tr>; })}{!loading && !attendance.length && <tr><td colSpan={5} className="py-10 text-center text-surface-500">No attendance has been recorded for your classes yet.</td></tr>}</tbody></table></div></section>
      <section className="card p-6"><h2 className="font-display text-lg font-semibold">Apply for leave</h2><p className="mt-1 text-sm text-surface-500">The admin will approve or reject this request.</p><form className="mt-5 space-y-4" onSubmit={submit} noValidate><label><span className="form-label">Leave type</span><select className="form-input" value={form.leaveType} onChange={e => setForm(v => ({ ...v, leaveType: e.target.value }))}><option value="SICK">Sick leave</option><option value="PERSONAL">Personal leave</option><option value="EMERGENCY">Emergency leave</option></select></label><div className="grid grid-cols-2 gap-3"><label><span className="form-label">From</span><input className="form-input" type="date" value={form.startDate} onChange={e => setForm(v => ({ ...v, startDate: e.target.value }))} /></label><label><span className="form-label">To</span><input className="form-input" type="date" value={form.endDate} min={form.startDate} onChange={e => setForm(v => ({ ...v, endDate: e.target.value }))} /></label></div><label><span className="form-label">Reason</span><textarea className="form-input min-h-24 resize-none" value={form.reason} onChange={e => setForm(v => ({ ...v, reason: e.target.value }))} /></label><Button type="submit" loading={saving} className="w-full"><Send className="mr-2 size-4" />Send leave request</Button></form></section></div>
    <section className="card overflow-hidden"><div className="p-6"><h2 className="font-display text-lg font-semibold">Your leave requests</h2></div><div className="table-wrapper border-x-0 border-b-0 rounded-none"><table className="data-table"><thead><tr><th>Dates</th><th>Type</th><th>Reason</th><th>Status</th><th>Admin note</th></tr></thead><tbody>{leaves.map(leave => <tr key={leave._id}><td>{new Date(leave.startDate).toLocaleDateString('en-IN')} – {new Date(leave.endDate).toLocaleDateString('en-IN')}</td><td>{leave.leaveType}</td><td>{leave.reason}</td><td><span className="badge badge-surface">{leave.status}</span></td><td>{leave.reviewNote || '—'}</td></tr>)}{!loading && !leaves.length && <tr><td colSpan={5} className="py-8 text-center text-surface-500">You have not submitted any leave requests.</td></tr>}</tbody></table></div></section>
  </div>;
}
