const express = require('express');
const router = express.Router();

// Import all module routers
const authRouter = require('../../modules/auth');
const usersRouter = require('../../modules/users');
const institutesRouter = require('../../modules/institutes');
const classesScheduleRouter = require('../../modules/classes-schedule');
const academicClassesRouter = require('../../modules/academic-classes');
const subjectsRouter = require('../../modules/subjects');
const liveClassesRouter = require('../../modules/live-classes');
const resourcesRouter = require('../../modules/resources');
const assignmentsRouter = require('../../modules/assignments');
const homeworkRouter = require('../../modules/homework');
const testsExamsRouter = require('../../modules/tests-exams');
const resultsRouter = require('../../modules/results');
const attendanceRouter = require('../../modules/attendance');
const feesPaymentsRouter = require('../../modules/fees-payments');
const chatRouter = require('../../modules/chat');
const doubtSessionsRouter = require('../../modules/doubt-sessions');
const notificationsRouter = require('../../modules/notifications');
const ptmBookingRouter = require('../../modules/ptm-booking');
const analyticsReportsRouter = require('../../modules/analytics-reports');
const inventoryRouter = require('../../modules/inventory');
const securityAuditRouter = require('../../modules/security-audit');
const integrationsRouter = require('../../modules/integrations');
const systemConfigRouter = require('../../modules/system-config');
const backupsRouter = require('../../modules/backups');
const broadcastRouter = require('../../modules/broadcast');
const dashboardRouter = require('../../modules/dashboard');
const uploadRouter = require('../../modules/upload');
const formsRouter = require('../../modules/forms/forms.routes');
const formSubmissionsRouter = require('../../modules/form-submissions/form-submissions.routes');
const examsRouter = require('../../modules/exams/exam.routes');
const questionBanksRouter = require('../../modules/exams/question-bank.routes');
const categoryRouter = require('../../modules/exams/category.routes');
const publicExamsRouter = require('../../modules/exams/public-exam.routes');
const leadsRouter = require('../../modules/leads/leads.routes');
const practiceRouter = require('../../modules/practice/practice.routes');
// Mount routes
router.use('/auth', authRouter);
router.use('/users', usersRouter);
router.use('/institutes', institutesRouter);
router.use('/academic-classes', academicClassesRouter);
router.use('/subjects', subjectsRouter);
router.use('/classes-schedule', classesScheduleRouter);
router.use('/live-classes', liveClassesRouter);
router.use('/resources', resourcesRouter);
router.use('/assignments', assignmentsRouter);
router.use('/homework', homeworkRouter);
router.use('/tests-exams', testsExamsRouter);
router.use('/results', resultsRouter);
router.use('/attendance', attendanceRouter);
router.use('/fees-payments', feesPaymentsRouter);
router.use('/chat', chatRouter);
router.use('/doubt-sessions', doubtSessionsRouter);
router.use('/notifications', notificationsRouter);
router.use('/ptm-booking', ptmBookingRouter);
router.use('/analytics-reports', analyticsReportsRouter);
router.use('/inventory', inventoryRouter);
router.use('/security-audit', securityAuditRouter);
router.use('/integrations', integrationsRouter);
router.use('/system-config', systemConfigRouter);
router.use('/backups', backupsRouter);
router.use('/broadcast', broadcastRouter);
router.use('/dashboard', dashboardRouter);
router.use('/upload', uploadRouter);
router.use('/forms', formsRouter);
router.use('/form-submissions', formSubmissionsRouter);
router.use('/exams', examsRouter);
router.use('/question-banks', questionBanksRouter);
router.use('/question-categories', categoryRouter);
router.use('/public/exams', publicExamsRouter);
router.use('/leads', leadsRouter);
router.use('/student/practice', practiceRouter);
module.exports = router;
